### ISSUE TITLE
Transform options not overriding default payload

### ISSUE THREAD

**Issue by xxtanisxx** [rollbar/rollbar.js#1026]
Unclear when this change was made. Previously, `transform()` would allow us to override default item payload. Now it no longer does this. 

At the current moment [`userTransform`](https://github.com/rollbar/rollbar.js/blob/a9c567cd1886f177fa4719a0054bff8280928fce/dist/rollbar.js#L1826)  comes before [`itemToPayload`](https://github.com/rollbar/rollbar.js/blob/a9c567cd1886f177fa4719a0054bff8280928fce/dist/rollbar.js#L1829) 

Wondering if we can move `userTransform` to the back of `itemToPayload`

Proposed Change:
```
    .addTransform(sharedTransforms.addConfiguredOptions)
    .addTransform(sharedTransforms.addDiagnosticKeys)
    .addTransform(sharedTransforms.itemToPayload)
    .addTransform(sharedTransforms.userTransform(logger));
```

**Comment by waltjones** [comment]
These have been in this order since at least the beginning of 2.x in 2017 (5 years ago.)

If your user transform function throws an uncaught error, the handler will remove the user transform from the config, and will log an error to the application log.

If you can show what your function is doing, maybe there is something more specific that has changed, or maybe an error is being raised.

**Comment by waltjones** [comment]
This order is now changed in v2.26.1 so that the custom transform can override the defaults.

**Comment by xxtanisxx** [comment]
oh wow. Thanks
