### ISSUE TITLE
Not an issue - awesome tool!

### ISSUE THREAD

**Issue by dandv** [rollbar/rollbar.js#108]
Migrated to Rollbar from Loggly and LogEntries.

Created a [Slant entry for Rollbar](http://www.slant.co/topics/2615/viewpoints/1/~what-are-the-best-javascript-client-side-error-logging-services~rollbar).

How does it [get error information from 3rd party scripts without the proper CORS setup](https://github.com/logentries/le_js/issues/51#issuecomment-121191747)?

**Comment by brianr** [comment]
Hey Dan - thanks for all the love!

The way this is working is:

- In the Rollbar snippet (the code we have you put in your `<head>`), we extend the prototypes of many global classes so that we can wrap `addEventListener`. [source](https://github.com/rollbar/rollbar.js/blob/master/src/globalnotifier.js#L26)
- Any event listeners which are added later will be instrumented with a try-catch. [source](https://github.com/rollbar/rollbar.js/blob/master/src/notifier.js#L806)
- Uncaught errors that happen in event listeners get intercepted in the try-catch, which is defined on the rollbar script source's domain, rather than bubbling all the way to `window.onerror`. I think this is the part that's enough to avoid the CORS restriction.
