### ISSUE TITLE
Is _rollbarConfig the only way to setup Rollbar.js?

### ISSUE THREAD

**Issue by gligoran** [rollbar/rollbar.js#131]
Hello,

I've got Rollbar all set and working in my Angular app, but the way it's set up is a bit of a pattern breaker for me. I'd like to know if there's any other way to set up ```accessToken```s, ```environment``` and other parameters that are in ```_rollbarConfig```. I'm especially interested in a way that will let me load Rollbar.js before setting up those parameters.

**Comment by Crisfole** [comment]
Hi there! If you *don't* have a `_rollbarConfig` object setup, then Rollbar will not initialize immediately. You'll have to call `Rollbar.init` later to get it started monitoring exceptions. `init` just receives the `_rollbarConfig` object.

You might be interested in the following UMD versions of the notifer, which fully load Rollbar without a subsequent load (no need for the snippet in your use case):

 * [rollbar.umd.js](https://github.com/rollbar/rollbar.js/blob/master/dist/rollbar.umd.js)
 * [rollbar.umd.nojson.js](https://github.com/rollbar/rollbar.js/blob/master/dist/rollbar.umd.nojson.js)

The second is if your Angular app is higher than 2.0. Since Angular 2.0 doesn't support <= IE 8, you'll be almost guaranteed to have a good JSON implementation and you can skip the shim we include y default.

**Comment by brianr** [comment]
@gligoran also take a look at these examples for browserify, webpack, and such: https://github.com/rollbar/rollbar.js/tree/master/examples

**Comment by gligoran** [comment]
Thanks guys. Got it working nicely.

**Comment by koenoe** [comment]
This works perfectly in the browser indeed, but in my Karma unit test it fails in PhantomJS:
```
[$injector:modulerr] Failed to instantiate module kroodle.core due to:
undefined is not a constructor (evaluating '$window.Rollbar.init(config)')
```
It seems to be that $window.Rollbar is all of a sudden an empty object instead of the Rollbar instance.

Examples:
[https://gist.github.com/koenoe/ea754b7cb52000b02074](https://gist.github.com/koenoe/ea754b7cb52000b02074)
[https://gist.github.com/koenoe/2051f76a8f29d984c2d1](https://gist.github.com/koenoe/2051f76a8f29d984c2d1)
