### ISSUE TITLE
1.6.1 in the readme

### ISSUE THREAD

**Issue by lookfirst** [rollbar/rollbar.js#134]
please

**Comment by coryvirok** [comment]
Hi @lookfirst,

I'm not sure what you're asking for. Are you seeing something from the v1.6.1 release that is not in the README?

**Comment by coryvirok** [comment]
nevermind, I see what you mean here: https://github.com/rollbar/rollbar.js/issues/135

**Comment by lookfirst** [comment]
No, these are two separate issues. This issue is that the readme was not updated with 1.6.1.

**Comment by coryvirok** [comment]
There aren't any changes necessary for the README with v1.6.1.

If you're referring to the CDN url that includes v1.6, we intentionally do **not** include the patch version so that we can deploy patch versions without customers requiring a change to the snippet code.

Is that what you are referring to?

**Comment by lookfirst** [comment]
I copy/paste the code from the readme into a .html file that I include with my projects. Your website is still reporting that I'm on 1.6.0 yet the latest version is 1.6.1.
