### ISSUE TITLE
new errors when I execute "rollbar.warning"

### ISSUE THREAD

**Issue by santomegonzalo** [rollbar/rollbar.js#178]
I made a handler to override browser warnings so every time I called console.warn('something') my handler will show the warning on console and will send it to rollbar. In the latest version I started to get this error after call console.warn('something'); 

`[Rollbar]: Error: No message, stack info or custom data(…)`

and this is my handler

```javascript
var exWarn = console.warn;
   console.warn = function() {
   exWarn.apply(this, arguments);
   window.rollbar.warning(arguments);
};
```

Thanks!

**Comment by Crisfole** [comment]
You don't say what the error is, but at first glance it looks like you've forgotten to use `apply` for rollbar's method too. Something like this should work fine:

```
var exWarn = console.warn;
   console.warn = function() {
   exWarn.apply(this, arguments);
   window.rollbar.warning.apply(window.rollbar, arguments);
};
```

**Comment by gsantome** [comment]
hello @Crisfole, thanks for you reply. I will try what you are saying... i dont know how that will affect because I'm just calling rollbar method. So the documentation said "Rollbar.warning('message')" and what im showing you used to work with the old version but with the new version I started to get a lot of errors until i get Max calls

the error is

`[Rollbar]: Error: No message, stack info or custom data(…)`

as you can see in this attachment

![img_01022016_090316](https://cloud.githubusercontent.com/assets/2914973/12719389/0b72fb9a-c8f5-11e5-964b-9b8212eb7afa.png)

thanks

**Comment by Crisfole** [comment]
Ah. Rollbar uses `console.warn` under the hood. That's what you're seeing.

As for `arguments`: arguments is an array. Sending an array will not result in what you expect (It will probably send fine, but will be grouped in an odd way).

**Comment by gsantome** [comment]
great... thanks @Crisfole your code fixed the problem. btw your product is great!
