### ISSUE TITLE
Is the Cloudfront distribution URL stable?

### ISSUE THREAD

**Issue by davewasmer** [rollbar/rollbar.js#195]
I've noticed that the Rollbar.js snippet loads the full library from a Cloudfront distribution (`https://d37gvrvc0wt4s1.cloudfront.net/js/v1.8/rollbar.min.js` specifically).

Does Rollbar guarantee that distribution will be the same in the future? If not, could you add a CNAME to provide a stable URL (i.e. `cdn.rollbarjs.com` -> whatever distribution is active).

---

**Edit:** for context, I realize that the snippet can be updated to point to a new distro URL, but in my case, I'm the author of `ember-cli-rollbar`, which would ideally be able to automatically add the appropriate Content-Security-Policy rules to the consuming Ember application. For that to work, I need to be sure that the domain the full library loads from is stable.

**Comment by dlsteuer** [comment]
Hi @davewasmer I apologize for the delayed response, but yes that url is stable.

**Comment by brianr** [comment]
To elaborate on that:

Eventually, we may change the snippet to use something like `cdn.rollbarjs.com` instead of the direct Cloudfront URL. However, there are thousands of websites that are using the snippet with the Cloudfront URL in it, and we are committed to making sure those continue working. For the foreseeable future, you can count on that URL being valid.
