### ISSUE TITLE
Snippet error's out in Karma CLI

### ISSUE THREAD

**Issue by rolandpeelen** [rollbar/rollbar.js#201]
We're using rollbar in conjunction with https://github.com/anotherpit/angular-rollbar
Basically it allows us to set the settings using angular based on production or development environment. But, the `this.$get` function errors out when running the snipped with the following error:

```
TypeError: undefined is not a constructor (evaluating 'a.loadFull(window,document,!_rollbarConfig.async,_rollbarConfig,i)')
```

In browser it works fine, but karma tests fail (sometimes). It looks like the loading of some of the snippet files doesn't work (or it tries to execute something before it's loaded). Sometimes it works, sometimes it fails. but it looks quite random.

**Comment by dlsteuer** [comment]
Hi @rolandpeelen 

Can you try loading Rollbar as a `umd` module instead of dynamically and see if that resolves your issue? This way it should always be available when the tests try to run. 

First go to https://github.com/rollbar/rollbar.js/blob/master/dist/ and grab the file you want to use (rollbar.umd.min.js or rollbar.umd.nojson.min.js). The nojson one is a bit faster, but you lose support for older browses. Then you use the same _rollbarConfig that you usually setup. If this exists on window (window._rollbarConfig) when the script is loaded it will configure itself automatically, otherwise you have to call Rollbar.init(_rollbarConfig). This allows you to manage your dependencies within Angular.

**Comment by rokob** [comment]
There hasn't been an update on this issue in a while, is this still a problem that you are having?

**Comment by pccjamie** [comment]
I'm experiencing something similar. In my case, I'm using another Angular wrapper: `ng-rollbar`, but the resulting issue is mostly the same. Rollbar receives my error payloads just fine. Seems like all init and config is fine. However, when running karma tests, I always get the following error:
```
Error: [$injector:modulerr] Failed to instantiate module my_module_name due to:
    TypeError: a.loadFull is not a function
        at Object.<anonymous> (bower_components/ng-rollbar/ng-rollbar.js:32:444)
```
I've opened an issue with that repo, but I'm uncertain if the issue is with rollbar or with the wrapper

**Comment by rokob** [comment]
I am pretty sure this is an error with the way these wrappers interact with angular and loading Rollbar.

**Comment by rokob** [comment]
Also `ng-rollbar` is pre-2.0 and most of the related code has changed quite a bit.
