### ISSUE TITLE
Rollbar breaks page loading in IE10+

### ISSUE THREAD

**Issue by alienisty** [rollbar/rollbar.js#203]
Rollbar affects page loading in IE 10+, specifically, the page readyState does not get pass the 'interactive' state, and as a consequence the 'loaded' event is never fired.

The following file [rollbar-ie-bug.zip](https://github.com/rollbar/rollbar.js/files/269750/rollbar-ie-bug.zip) contains a very simple HTML file that reproduces the problem.

If you remove the rollbar snippet, the alert is shown and the status will be 'complete'. With the rollbar snippet, the alert does not show and the status will be 'interactive'.

Note that the HTML with rollbar works fine in IE 9.

**Comment by Crisfole** [comment]
@coryvirok, @jondeandres related to #199 ?

**Comment by dlsteuer** [comment]
Hi @alienisty, thanks for the HTML file, I grabbed that and tried to replicate this in my own environment, I tried it with an IE10 VM provided by Microsoft from http://modern.ie and on IE11 on my Win 10 box, but was unable to replicate the issue here. Is there any additional information that you can provide so we can get this fixed?

**Comment by alienisty** [comment]
Hi @dlsteuer, I since reset IE settings to default and the problem did not happen again. I think I changed some of the security settings before the problem started, but I can't remember the details for sure.

**Comment by dlsteuer** [comment]
I'm going to close this for now then, let us know if this happens again to you, and if so what settings you have set for IE.
