### ISSUE TITLE
Permission denied to access property "_rollbar_wrapped"

### ISSUE THREAD

**Issue by ochanje210** [rollbar/rollbar.js#391]
I am testing a web application written in javascript using multi-platform browser testing service, CrossBroswerTesting, and keep having the following issue:

```WebDriverException: Unable to execute javascript: "return Math.max(window.document.body.offsetWidth,window.document.body.scrollWidth, window.document.documentElement.offsetWidth, window.document.documentElement.scrollWidth);" -> Error: Permission denied to access property "_rollbar_wrapped"```

from the following environment:
- OS: Windows 8.1
- browser: Firefox (53.0) 64-bit

**Comment by ekampp** [comment]
I can confirm that this is also a thing for Win 10, FF 52.

**Comment by igrishaev** [comment]
Same on Mac, Firefox 52

**Comment by rokob** [comment]
This is not a Rollbar bug, this is one of two things: 1) a same-origin issue due to your accessing the window property and we just happen to be wrapping it, 2) a Firefox issue being overly aggressive. See for instance https://github.com/facebook/react/issues/10181 https://github.com/getsentry/raven-js/issues/768 https://github.com/angular/protractor/issues/4272

Rollbar code shows up because we wrap some things but the underlying issue is somewhere else.
