### ISSUE TITLE
Use a local version of Rollbar

### ISSUE THREAD

**Issue by XavCamp** [rollbar/rollbar.js#396]
Hi!
I'm using Rollbar by downloading and serving the source from our server. It works basically just calling `new window.rollbar(my_options);` after synchronously loading rollbar.min.js
But with the Telemetry update, I see that I'm missing some events listener that are set in the snippet. I can't use the snippet because it tries to download the source, and I need to do that myself.
So my question is, could we have a version of the snippet that would set all the listeners but not try to download the script? Would that be a usage you would support?
I can just manually edit the snippet, but I would have to do it at each release of Rollbar.
Thanks!
Xavier

**Comment by rokob** [comment]
There are two events that the snippet gathers that the main source does not and both are related to onload. It doesn't make sense to put those in the normal rollbar source because it is typically loaded asynchronously. I am not sure what we can do for you exactly at the moment but it would be quite simple to add your own event listener for the onload event and add that data to the telemetry events if it is vital for you. Based on the way you are loading things, if Rollbar is loaded at all then you basically know the onload event succeeded, so it is a bit superfluous.

**Comment by XavCamp** [comment]
So I just need to copy the onload event listeners from the snippet to have all functionalities without using the snippet?
I think that will work for me.
Thanks for the quick help!

**Comment by joostbaptist** [comment]
@XavCamp Did you ever figure out how to do this?

**Comment by XavCamp** [comment]
@joostbaptist As it was suggested, I just synchronously load `Rollbar.js`, then manually add the load listeners that Rollbar snippet is supposed to add:
```js
window.addEventListener('load', _rollbar.captureLoad.bind(_rollbar));
window.addEventListener('DOMContentLoaded', _rollbar.captureDomContentLoaded.bind(_rollbar));
```
Then call `new window.rollbar(my_options);`
