### ISSUE TITLE
Telemetry `rollbar.captureEvent(...)` throws `Rollbar is not initialized`

### ISSUE THREAD

**Issue by lukasmlady** [rollbar/rollbar.js#440]
I'm following "Quick start Browser" from https://rollbar.com/docs/notifier/rollbar.js/, using:
```
<script>
var _rollbarConfig = {
    accessToken: "POST_CLIENT_ITEM_ACCESS_TOKEN",
    captureUncaught: true,
    captureUnhandledRejections: true,
    autoInstrument: true,
    payload: {
        environment: "production"
    }
};
// Rollbar Snippet
!function(r){function o(n){if(e[n])return e[n].exports;var... // omitted
// End Rollbar Snippet

// This throws "Rollbar is not initialized".
rollbar.captureEvent({somekey: 'somevalue'}, 'debug');

// This works and shows correctly in Telemetry.
Rollbar.impl.captureEvent({somekey: 'somevalue'}, 'debug');
</script>
```

Rollbar.js works as expected but:

1. Using `rollbar.captureEvent(metadata, 'debug')` throws `Rollbar is not initialized` after page load, run manually in console and at any point in time in the page lifecycle. This is documented in the Telemetry section of the docs - https://rollbar.com/docs/notifier/rollbar.js/#telemetry.

2. Using `Rollbar.impl.captureEvent(metadata, 'debug')` works perfectly fine, but this is an undocumented piece of API.

**Comment by rokob** [comment]
It is a bit confusing, but `rollbar` is the top level module and `Rollbar` is a specific instantiated instance. The methods on `rollbar` like `captureEvent` can only be called directly if you have called `rollbar.init(options)`.

As a separate point, you should be able to call `Rollbar.captureEvent(metadata, 'debug')` and that is a bug that you cannot. The fix is https://github.com/rollbar/rollbar.js/pull/443

**Comment by lukasmlady** [comment]
@rokob yeah, usually the naming is done in exactly the opposite way, but I understand that is not something to be changed any time soon.

Looking forward to #443 merged.
