### ISSUE TITLE
Sourcemaps for iOS in Ionic

### ISSUE THREAD

**Issue by cmorales** [rollbar/rollbar.js#453]
Hello everyone,

I am trying to have the sourcemaps working for iOS, being built for Ionic and sending the sourcemaps from my gulp task.

For Android is working. Im having the same problem with this:  '-F minified_url=file:///android_asset/www/js/app-min.js ' +

For android is good, but for iOS, I don't know what to set, since a different hash is always generated.

`'curl https://api.rollbar.com/api/1/sourcemap ' +
                    '-F access_token=ab07de9b66124704abc026c49dd9c33c ' +
                    '-F version=' + RollbarVersion + ' ' +
                    '-F minified_url=file:///android_asset/www/js/app-min.js ' +
                    '-F source_map=@www/maps/app.js.map';
`

Im sending this to Rollbar from gulp.

But at the end it doesn't get transformed properly for iOS, I need the solution for iOS.

This is how the filename looks in Rollbar for errors for iOS:

file:///var/containers/Bundle/Application/FF2A5FDB-AD30-477D-BBC4-DDAA289B949A/Dream%20Leagues.app/www/js/app-min.js

I would need that to be somehow unique.

I saw a similar issue here https://github.com/rollbar/rollbar.js/issues/65 but I don't understand how to implement the solution given there.

Any help would be highly appreciated.

Thanks in advance.

**Comment by rokob** [comment]
The solution in #65 is to use the configuration option of a transform function which has access to the full payload prior to sending it to Rollbar. One can iterate through the frames in the stack trace included in the payload body and rewrite the filename to anything you want. So instead of setting the minified_url when you upload the source map to something that will match the generated location based on a random bundle identifier, you can change the filename on each frame to be something specific and then use that as the minified_url for your source maps.

**Comment by cmorales** [comment]
Can you give me more information about that?

Where shall I put that transform function? What kind of code is it? 

I am totally lost with that piece of code, I dont know where I should place it at all.

**Comment by rokob** [comment]
Wherever you are including the Rollbar javascript there must be some sort of configuration being passed in. Inside that configuration you can set a property with name `transform` to a Javascript function which takes the payload as an argument and modifies it in-place. The code in the aforementioned issue is coffeescript but the idea in javascript would be the same. You can see https://github.com/rollbar/rollbar.js/blob/master/src/react-native/transforms.js#L102,L135 which is some react-native related code that we have for doing a transform like that.
