### ISSUE TITLE
Explicit calls not making it to Rollbar with a page reload

### ISSUE THREAD

**Issue by and-megan** [rollbar/rollbar.js#475]
Rollbar is loaded through Segment using device mode. 

Rollbar.log('log') and immediately after that do a page reload. The problem is that the request to the Rollbar API to log the error is canceled because of the window reload. Never get logs on my dashboard. UUID is returned before the request succeeds. Can we write errors on a persistent storage before sending them? 

$.ajax().then(function(){Rollbar.log(); reloadPage()})

Intercom convo: https://app.intercom.io/a/apps/rlisg82q/respond/inbox/488687/conversations/12415407990

**Comment by rokob** [comment]
Hey so I see three possible approaches to this:

1. All Rollbar method calls (log/error/warning/etc.) accept a callback argument. This callback will be called with an error, null on success, and the server response, null on failure. You can therefore use this callback to know when the method has actually succeeded or failed and wait to perform the reload/transition until the log goes through.

2. You can use the aforementioned callback mechanism to build your own layer of persistence using local storage on top of Rollbar.

3. We can build in the ability to persist items to local storage before sending and then sync that queue of items every time we are loaded.

1 and 2 you can get today, 2 requiring a bit more work than 1. As to 3, we are going to put this functionality on our roadmap as it is an understandable feature. However, it will add a non-trivial amount of complexity and is not a cost that the normal use case should have to pay, so it will take some time to get right.

**Comment by kwstoikonomou** [comment]
have you thought of having async log/warn/error functions so we can use then/await operators on them?
A callback will do for now (i will actually create a wrapper so i can have a promise) but it is not something i like using and i guess a lot of people fill the same way

**Comment by aharpervc** [comment]
What about the possibility of using navigator.sendBeacon?

**Comment by rokob** [comment]
`navigator.sendBeacon` is supported in most of the modern browsers (https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) so we could work that in. For the specific use case of logging then doing a reload, we can already do that with the callback api. We have to target an old set of potential users so the async/await style is not available to us unfortunately. Writing a simple wrapper in your own code that uses the async/await style as an interface and uses our callback underneath should be pretty straightforward. I'm going to close this specific issue because what it is asking for is already possible. For doing persistence that is covered in a separate issue.
