### ISSUE TITLE
we're trying to handle rejected promise cross domain

### ISSUE THREAD

**Issue by and-megan** [rollbar/rollbar.js#488]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Property_access_denied

Error: Permission denied to access property "reason"

@rokob I know you're aware of this one, just created this for tracking purposes.

**Comment by black-orchid** [comment]
We're also having this error, only from firefox browsers in version 2.2.9 of rollbar.js.

**Comment by alexblack** [comment]
Also seeing this

**Comment by rokob** [comment]
Okay I know where this is coming from in our code. I have a fix. It is less than satisfactory as this error means a promise is being rejected in some script that is violating the same origin policy (either in an iframe or just a script loaded cross domain). You could have some error going on, but due to the browser security model we won't be able to tell you much more about it. My fix will alert you that this is happening and won't throw this particular exception, but nonetheless there is only so much information that we can get.
