### ISSUE TITLE
Throw error or send message to Rollbar's API when script doesn't execute

### ISSUE THREAD

**Issue by and-megan** [rollbar/rollbar.js#496]
For cases like this, send a message instead of silently ignoring:

Executing that function f looks like it will throw an exception in the first statement r() because r is undefined. We currently ignore the checkIgnore if it throws. 

window.Rollbar.options.checkIgnore
ƒ (e,n,t){if(r())return!0;var a=t.request,b=t.body;if("warning"===t.level)return!0)...

https://app.intercom.io/a/apps/rlisg82q/respond/inbox/813334/conversations/12679623684

**Comment by jonathanong** [comment]
actually i don't think you're right. i added tests on the minified file and it works fine. 

what you see when you type `_rollbarConfig.checkIgnore` is only the function itself, but nothing outside its scope. ex. the function is like:

```js
const r = require('./check-browser')

module.exports = (a, b, c) => {
  if (!r()) return false
  // rest of the code
}
```

**Comment by rokob** [comment]
I'm looking into this, I can't see any obvious reason why the checkIgnore would not be called, still digging.

**Comment by rokob** [comment]
I've tested the checkIgnore function and it should be working, are all of the instances of things not working properly happening at load? How are you loading Rollbar and configuring it? Is your checkIgnore function set with a call to configure after initializing Rollbar?

**Comment by jonathanong** [comment]
i've added console logs and seen `checkIgnore()` not get called at all for an error and that error not getting sent. i am, however, getting errors in my rollbar project

**Comment by rokob** [comment]
That is super weird. The checkIgnore function does run pretty late in the processing pipeline, so if for example the item has a level lower than the configured reportLevel then the checkIgnore function will never get called. That being said that specific case is probably not what is going on here.

If you set the checkIgnore function via a call to configure, it is technically possible to have a race condition with errors that get processed before that call to configure, so if it is an error very early then it might not get the checkIgnore function yet. For why it wouldn't be sent at all I can't imagine. One possible way to debug would be to turn verbose to true which should emit logging statements if we gave up on processing something due to an exception that occurred in the pipeline, for example when trying to process the stack trace.

**Comment by jessewgibbs** [comment]
@jonathanong were you able to get this issue resolved?  We've not heard back from you in a while...

**Comment by jonathanong** [comment]
we're not seeing `checkIgnore()` being called many times when we pass an error, even if `checkIgnore()` is an empty function. you haven't heard from us because we gave up on this and are living with noise :P
