### ISSUE TITLE
Get server-side reporting to work with Nuxt.js

### ISSUE THREAD

**Issue by and-megan** [rollbar/rollbar.js#528]
https://nuxtjs.org/
 Nuxt catches it and shows an error page. Rollbar never has a chance to touch it. 

It looks like Nuxt loads it's own middleware after it loads Rollbar's handler so Rollbar gets outcompeted: https://github.com/nuxt/nuxt.js/blob/ce4b971640cb9ece0adce9e4d79477cc26147e7c/lib/core/renderer.js#L267-#L279

internal: https://app.intercom.io/a/apps/rlisg82q/respond/inbox/488687/conversations/13481293311

**Comment by jehoshua02** [comment]
@and-megan heads up - [Nuxt.js 1.0 is out](https://medium.com/@nuxt_js/nuxt-js-1-0-is-out-bab1af459972).

**Comment by aldarund** [comment]
nuxt 1.4 out some time ago. And nuxt 2.0 incoming pretty soon.

**Comment by jehoshua02** [comment]
@and-megan we are building another project with Nuxt. Curious to see if there's been any progress on this issue.

**Comment by and-megan** [comment]
Hey @jehoshua02 - I'm not sure. @rivkahstandig3636 do you know if there's any work on this?

**Comment by rokob** [comment]
You can do this already, I'm a little confused at what the issue is here? Is this just a documentation question?

I've never used nuxt but briefly looking around, there is a mechanism for executing whatever you want in the event of an error.

You can add an error middleware which will get called before the built-in one due to: https://github.com/nuxt/nuxt.js/blob/d98c98360ab614f95c461b1e8bf871ee505211ec/lib/core/renderer.js#L275,L276

Create a module, register for the `render:errorMiddleware` event in a hook https://nuxtjs.org/guide/modules#run-tasks-on-specific-hooks, then in that function you can call `app.use` with a relevant plugin.
