### ISSUE TITLE
Winston support

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/rollbar.js#535]
Original report: https://app.intercom.io/a/apps/rlisg82q/respond/inbox/488687/conversations/13689108280

**Comment by rokob** [comment]
The winston-rollbar library linked in that conversation is https://github.com/GorillaStack/winston-rollbar/blob/master/package.json which uses rollbar.js version 2.1.3, it does not use node_rollbar even though the README says it does. There isn't anything to do other than maybe bump that version.

**Comment by alonisser** [comment]
The discussion started from the need to change to lib used, since we are getting deprecated warnings and with the question how can this be done or helped

**Comment by rokob** [comment]
The fix for this is to update the the winston-rollbar library rather than do anything here.

**Comment by alonisser** [comment]
Of course this is not about updating here. this thread was created since there is no current updated winston integration without deprecation warning, which makes  rollbar a no go compared for example to sentry (https://www.npmjs.com/package/winston-raven-sentry) or other alternatives. You want us to use your product? make it simple for us. 
I'm planning to move our company of rollbar, with this kind of node.js support
