### ISSUE TITLE
Rollbar 2.3.6 not working with Angular 5 while running in Production build

### ISSUE THREAD

**Issue by atulkumar** [rollbar/rollbar.js#554]
Error is coming like ERROR in : Error: Internal error: unknown identifier null
    at Object.importExpr$$1 [as importExpr] (..\node_modules\@angular\compiler\bundles\compiler.umd.js:30942:23)

I tried with 2.3.3 version but no luck :(

Anyone facing same issue?

**Comment by douglasward** [comment]
Yes, I'm facing this as well.

**Comment by douglasward** [comment]
Just got my integration working. 

I had used this blog post to set up rollbar in my app: https://rollbar.com/blog/client-side-angular-error-handling/

But it is missing the `export const RollbarService = new InjectionToken<Rollbar>('rollbar');` line.

and provides `Rollbar` instead of `RollbarService` in the AppModule.

The correct set up is detailed here: https://rollbar.com/docs/notifier/rollbar.js/#angular-2-and-later

**Comment by jessewgibbs** [comment]
@atulkumar could you have a look at https://rollbar.com/docs/notifier/rollbar.js/#angular-2-and-later and let us know if that solves your issue?
