### ISSUE TITLE
Rollbar prevents original log origin from being shown in browser console

### ISSUE THREAD

**Issue by bryandh** [rollbar/rollbar.js#575]
After using Rollbar for a while, all the regular `console.log` calls are being shown as originating from `rollbar.min.js:2251:82`. If I understand correctly, this is caused because Rollbar overrides the `console.log` function and handles the logging by itself. However, I would like to still be able to see where the log came from, for instance from `heading.ts:25`, this can be helpful in some instances.

I have tested this in Chrome, Firefox and Safari on MacOS with the latest Rollbar snippet. Once I remove the snippet, the log origin is back to normal again.

Is there a way to maintain the log origin in the browser console?

**Comment by DRSisco** [comment]
Setting this up for Angular 4. 

Noticed if you
```ts
export let rollbarConfig = {
    captureUncaught: environment.production,
    captureUnhandledRejections: environment.production,
    enabled: environment.production
}
```
Then rollbar will only catch errors in production when it is also sending them to rollbar.
I suppose this doesn't fix the issue if you are trying to recreate a production only issue. 
However I just want to see this errors in development, when I testing locally.

**Comment by rokob** [comment]
The only thing you can do is turn off log auto instrumenting which will stop us from wrapping the console methods. We only wrap the console methods for gathering telemetry data, it isn't used for sending things to Rollbar, so that would give you the correct log location in the console with the only side effect being those console messages would not show up in the telemetry logs.

```
{
    ....
    autoInstrument: {
        log: false
    },
}
```
