### ISSUE TITLE
"SOMError 1001: Invalid Account" Error after updating to the latest version.

### ISSUE THREAD

**Issue by AlexVentura** [rollbar/rollbar.js#590]
I was using rollbar.js `version 2.2.7` in my project.
So, I updated the snippet to the actual one as described in the README file under [Quick start Browser](https://github.com/rollbar/rollbar.js#quick-start-browser) section.

Now on the browser I got this log with a kind of error:

```
SOMError 1001: Invalid Account
```
<img width="1417" alt="screen shot 2018-03-27 at 20 58 21" src="https://user-images.githubusercontent.com/13169164/38008241-db973c48-320a-11e8-9fba-d67916f44a40.png">

Overall the script seems to work because after testing as described in the documentation the logs are reflected in the Rollbar dashboard.

I've searched in the documentation but I can't find anything related.
Can you help me out with that? How can I fix this error?

**Comment by rokob** [comment]
That is not an error related to Rollbar. Due to the way telemetry works, console messages appear to be coming from rollbar.js. You can turn that behaviour off by turning off log auto instrumentation using something like the configuration below (depending on how you actually configure things).

```
_rollbarConfig = {
  ...
  autoInstrument: {
    log: false
  }
  ...
}
```

Looking at your screenshot, you get a 403 from intercom and then it logs that message, so maybe it is coming from there. This is not an issue with rollbar.js however.

**Comment by AlexVentura** [comment]
@rokob I think it actually is a log from `rollbar.js` log, at least, as you can see in the picture below, the log now comes before the _iterncom_ log so I think this call is nothing to do with rollbar.
But ok, thanks for your response.

<img width="1421" alt="screen shot 2018-03-28 at 14 20 59" src="https://user-images.githubusercontent.com/13169164/38054241-9dc6465a-3293-11e8-99ee-43ade39e7a1b.png">
