### ISSUE TITLE
codeVersion vs. code_version

### ISSUE THREAD

**Issue by naartjie** [rollbar/rollbar.js#595]
In the [Readme](https://github.com/rollbar/rollbar.js/blame/ebe145cba949c9214fd660263e974da59010524d/README.md#L827-L830) it says:

> Note: `codeVersion` will not work, you must use `code_version`

but I find the opposite works, I'm using version `2.3.9` in node:

```js
const rollbar = new Rollbar({
  environment: CURRENT_ENV,
  accessToken: TOKEN,
  captureUnhandledRejections: true,
  codeVersion: GIT_SHA,
});
```

It looks like `code_version` is set to `options.codeVersion` [here](https://github.com/rollbar/rollbar.js/blob/ebe145cba949c9214fd660263e974da59010524d/src/server/transforms.js#L20).

**Comment by rivkahstandig3636** [comment]
We will take a look into this, sorry for the delay!

**Comment by rokob** [comment]
Yeah it is `codeVersion` I believe to match the style of camel case in JavaScript. The API requires `code_version` which is why we set it to that when building the payload. I'm not sure what we want to do here. We could just change the docs to say use codeVersion, we could change the config to use code_version, we could change the config to support both snake and camel case.

**Comment by rivkahstandig3636** [comment]
I vote we change the config to support both & update the docs

**Comment by rokob** [comment]
Ok so I looked into it, the docs are correct. Putting `codeVersion` at the top level of the configuration happens to work, but that is not documented anywhere. In the docs it says that `code_version` nested under the `payload` key will work and that is true. If you use `codeVersion` nested under the `payload` key that will not work. I am going to clean this up a bit.
