### ISSUE TITLE
TypeError: "fetch" is read-only in Firefox Web Extension content script

### ISSUE THREAD

**Issue by csergiu** [rollbar/rollbar.js#638]
I don't understand why it's giving me this error. I've installed the package from npm and I'm using Browserify and Babelify to compile my scripts. I feel like this is a bug as I feel like I'm doing everything right? The error seems to be at the replace() function definition of the browser/telemetry.js file: https://github.com/rollbar/rollbar.js/blob/3950a56aac531c8c16e4a3f635d8e1fdae37fd73/src/browser/telemetry.js#L18

It seems to be working just fine in Chrome, while in Firefox it's giving me this error. Can someone help me with this? I've tried:

- loading the Rollbar library as a separate content script
- using a fetch-polyfill
- using babel-polyfill

**Comment by rokob** [comment]
If you are running as a content script in Firefox rather than directly as a script then I would expect trying to replace fetch on the window global would be problematic. For an immediate fix I would say set the network autoInstrument setting to false, this will prevent us from running that code. For a longer term fix we should probably have a try/catch around that replace for this issue.

**Comment by csergiu** [comment]
Thank you @rokob! That fixed it.

**Comment by jessewgibbs** [comment]
@rivkahstandig3636 is there any more work to do in this issue?  It looks like it's fixed...

**Comment by rivkahstandig3636** [comment]
@jessewgibbs Nope, it can be closed. Oversight on my part, thanks for noticing!

**Comment by Mathieuu** [comment]
I encountered the same problem:
- In a firefox addon content script, fetch cannot be replace as it is read-only

It there is no fix for that, could at least catch the error and have a better logging for it? It is nested pretty deep inside the library and for some reason, Firefox sometimes swallow the error which lead to manual debugging.
