### ISSUE TITLE
Confusing error - "item per minute limit reached, ignoring errors until timeout"

### ISSUE THREAD

**Issue by Bomper** [rollbar/rollbar.js#648]
I got this error among my items for a Node.js project, and couldn't tell what caused it. There was no filename or line. Turns out it comes from Rollbar's own [rateLimiter](https://github.com/rollbar/rollbar.js/blob/307aa19ec6cf14a3334936bcf0792a6577968376/src/rateLimiter.js#L105).

What does this error mean? There are no other items that occurred in the few hours prior to this error, so I don't see how any sort of rate limit might have been reached. I was on the free trial, which expired some ~18 hours after this error was logged.

Also, I feel this should be a separate type of error. Right now it looks just like any other error sent by my application (except that there's no IP address for it).

**Comment by rokob** [comment]
I'm seeing now that this could theoretically happen if you have an error, but the network request fails for some retriable condition, like the network is done, and then we keep trying to send that item, but by the time we get the network back we have already tried to send it more than the rate limited number of times in a minute which results in the rate limit item. Otherwise, there is no way to see this without getting more than 60 items per minute, unless you configured the `itemsPerMinute` option to be less than 60.

**Comment by Bomper** [comment]
Interesting... I haven't touched `itemsPerMinute` and the Node.js script it running on DigitalOcean, which shows no outage recently. https://status.digitalocean.com.

**Comment by jessewgibbs** [comment]
I'm going to close this issue since PR #649 includes some changes to address it.  If this continues to occur, please let us know.
