### ISSUE TITLE
what would happen when I use both hostBlacklist and hostWhitelist at the same time?

### ISSUE THREAD

**Issue by wildskyf** [rollbar/rollbar.js#652]
I add "domain1.com" into the array of hostWhitelist, and add "domain2.com" into the array of hostBlacklist.

Now there is an item whose filename of trace contains both "https://domain1.com/index.js" and "https://domain2.com/index.js", will this item be sent to server?

**Comment by rokob** [comment]
As the code is currently it will not get sent because of the blacklist.

Blacklist is do not send items if they contain a filename in the trace that matches an item in the list.
Whitelist is do not send items unless a filename in the trace matches an item in the list.

They can both be thought of as filter predicates and therefore if either predicate fails the item will not be sent.

**Comment by rokob** [comment]
Whether that is obvious or fully desirable is another question. I am not sure what the natural expectation or right answer is here.

**Comment by wildskyf** [comment]
got it, It does match my anticipation.

Thanks for your explanation. :)
