### ISSUE TITLE
networkResponseHeaders, networkRequestBody, networkResponseBody not returning extra Information

### ISSUE THREAD

**Issue by ajtran** [rollbar/rollbar.js#667]
internal - https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/849049/conversations/18343718932

In a simple React app that makes an HTTP Request to https://api.github.com, the telemetry data associated with an error that occurs shortly after this call is not populated with `networkResponseHeaders`, `networkRequestBody`, and `networkResponseBody`. The telemetry data looks the same as if these values were all turned off in the configuration. 

This is the configuration used to test:
```
autoInstrument: {
  dom:false,
  log:false,
  network:true,
  navigation:false,
  connectivity:false,
  networkResponseHeaders:true,
  networkResponseBody:true,
  networkRequestBody:true
},
```
I was hoping someone could take a look at this and get this working.

**Comment by jessewgibbs** [comment]
@shakiba could you investigate this? @ajtran was able to reproduce the customer issue and can provide more context.

**Comment by rokob** [comment]
Do you have a sample app that reproduces this? The only thing I could think was that this was related to a race condition, but in investigating that I am pretty sure the race I thought was possible is not. The examples I have tried I either have no network request data in the telemetry events if the request hasn't finished in time or I have data and it includes the body and headers given that configuration. Those options don't work so well on Internet Explorer or if you use `fetch` instead of XHR. Could those be possibilities?

**Comment by jessewgibbs** [comment]
I'm closing this issue since there's been no response from the original reporter.
