### ISSUE TITLE
Re-add Webpack Example

### ISSUE THREAD

**Issue by jessicahsieh** [rollbar/rollbar.js#691]
used to be here: https://github.com/rollbar/rollbar.js/tree/v2.3.3/examples/webpack

now it is not

**Comment by jessewgibbs** [comment]
@rokob any ideas why the Webpack example was removed?

**Comment by rokob** [comment]
Yeah it was removed because I think it doesn't work and it isn't really a complete webpack example as the webpack config isn't there. I think the idea was that people were asking questions about it because it was broken so I thought it was better to remove it as it was more confusing, but I should have added a working one. I just never got around to it.

**Comment by jessewgibbs** [comment]
Got it.  I'll switch this to being an enhancement.  For now, I'm going to hide the Webpack docs until we fix the example.

**Comment by jessicahsieh** [comment]
following up with this: i have another customer requesting an example webpack configuration. have you had a chance to work on it?

**Comment by bradrobertson** [comment]
Ya I've just spent a bunch of time now being redirected to pages that redirect back to other pages that have missing examples for webpack, so that's been pretty frustrating. 
The react docs just link back to the main JS docs, and the browserify example suggests:
> rollbar.js is also distributed using UMD, so you can use it with browserify, requirejs, webpack, or anything else that uses AMD or CommonJS modules. See the examples for details.

But when you go to the examples, there's no working webpack example.

**Comment by bradrobertson** [comment]
Is there any movement on this?
