### ISSUE TITLE
Rollbar wait(...) type definition

### ISSUE THREAD

**Issue by ryanburr** [rollbar/rollbar.js#705]
When trying to use rollbar with typescript, I noticed that there is no method for `wait(...)` in the type definition file. 

Looks like a pretty easy one to add. Should just be

```js
...
public wait(callback: () => void): void;
...
```

**Comment by jessewgibbs** [comment]
@waltjones do you mind adding this?  We might want to check for other missing entries in the type definition file too.

**Comment by waltjones** [comment]
@jessewgibbs, @ryanburr has a PR open. I'll review and look for anything else missing.

**Comment by rokob** [comment]
I just merged that PR because it was straight forward. We should probably still do a pass looking for anything else missing. I made this issue a while ago https://github.com/rollbar/rollbar.js/issues/541 to remind myself to see if we can automate this so we don't miss anything but I never got around to it.
