### ISSUE TITLE
Support for extensions that use content scripts in Chrome 73+

### ISSUE THREAD

**Issue by brianr** [rollbar/rollbar.js#708]
Starting in Chrome 73, content scripts are subject to the same restrictions as the web page they are injected to: https://developer.chrome.com/extensions/xhr

We'll need a story for how to use rollbar.js in this environment. A few possibilities to investigate:

- Can the content script make a request to rollbar.js through a background script controlled by the extension?
- Can this problem be resolved by changing the permissions in the extension's manifest file?
- any other possibilities?

internal reference: https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/conversation/21124593812

**Comment by waltjones** [comment]
My testing appears to show the Rollbar API is not affected by this Chrome policy change because Rollbar API already sends the correct cross origin headers. (The Chrome update _will_ affect network responses that do not include the correct headers.) 

The referenced PR adds a Chrome extension example containing both a background script example, and content script example. These were found to work as expected both pre and post Chrome 73.

**Comment by brianr** [comment]
Great work @waltjones. That's the conclusion we've drawn from the original customer question as well. Once #708 has been merged and documented, let's close this out.
