### ISSUE TITLE
Sourcemapping with Create React App

### ISSUE THREAD

**Issue by jarretmoses** [rollbar/rollbar.js#728]
I apologize in advance if this is not the right medium for this question.

**Problem**: Production Sourcemaps from Create React App not being detected by Rollbar

**Description**: I am running the production builds for Create React App which generates hash value name spaced file such as `main.e322d9a0.chunk.js`, which has a corresponding sourcemap (worth noting the hash value changes on every build). However, when an error is thrown, Rollbar does not seem able to detect the sourcemaps. Specifically in the Error on the dashboard I see `Source maps were not available for some minified Javascript files in this traceback` and in the `Source Maps` tab I see an error from my js file stating `HTTP unknown for minified JS file at path/to/file`

**Question**: What do I need to do in order for sourcemaps to be detected. I looked at documentation but not fully graspong what I am doing wrong here. I did see somethign about enabling `"client.javascript.code_version"` with a `SHA` is this the value generated by CRA? I did notice I can manually make Rollbar aware of source maps but would prefer through a config if possible. 

**Current Config**: 
```
export const rollbar = new Rollbar({
  accessToken: process.env.REACT_APP_ROLLBAR_ACCESS_TOKEN,
  captureUncaught: true,
  captureUnhandledRejections: true,
  payload: {
    environment: Environments.Production,
  },
  enabled: process.env.NODE_ENV === Environments.Production,
});
```

**Comment by jessicahsieh** [comment]
Issue has come up a couple times on Intercom as well:

https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/search/conversations/21823847961
https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/search/conversations/22040786075
https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/search/conversations/22007349836

**Comment by letaniaferreira** [comment]
https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/849049/conversations/22040786075

**Comment by jessicahsieh** [comment]
another one - 
https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/813342/conversations/22081332435

**Comment by waltjones** [comment]
I've had a chance to try this out with Create React App, and I didn't find any issues related to Create React App itself. In short, source maps should work as well - and the same way - as in other JS apps with source maps. I have made my own list of possible gotchas though, and in general these could apply to anyone using source maps with Rollbar for the first time. 

1) You must add a version to your Rollbar.js config, and it must match the version your maps are tagged with.
```
      config = {
        accessToken: 'token',
        captureUncaught: true,
        captureUnhandledRejections: true,

        payload: {
          client: {
            javascript: {
              code_version: '42',
              guess_uncaught_frames: true
            }
          }
        }
      }
```
You get to choose your version string yourself, but if it's missing or the value is different than what you add to your source maps, the correct source map(s) won't be found to be applied to the error event.

2) When using curl to upload source maps, you must construct your options so that they are valid curl options. This makes use of the `-F` options, which can be tricky to use.
```
curl https://api.rollbar.com/api/1/sourcemap \
  -F access_token=my-token \
  -F version=42 \
  -F minified_url=file:///home/walt/projects/rollbar/cra/build/static/js/main.ad5edc14.chunk.js \
  -F source_map=@build/static/js/main.ad5edc14.chunk.js.map \
  -F App.js=@src/App.js \
  -F serviceWorker.js=@src/serviceWorker.js \
  -F index.js=@src/index.js
```
For the first three options, `access_token`, `version`, and `minified_url`, we are sending plain strings. curl will not try to read any data from the location specified by `minified_url`, it just sends the string you give it. This string _must_ match the full path that appears in the stack trace that gets sent to Rollbar when there is an exception. Look at your raw exceptions (without source maps applied) if you are unsure what the paths will look like. My example above shows that I am running the app locally. In production, that is going to be in the format 'https://...' instead. Either way, it must match the full paths that appear in the Rollbar stack trace.

The next four options use the `@` character to prefix the path. These are sent as file attachments, and the full contents of the file will be sent. If you use relative paths, the paths have to be correct for what ever location you're running curl from. If you use absolute paths, the current dir doesn't matter, though the file does need to exist.

3) The `source_map` option must point to the source map file on disk.
Most people get this one right, but for completeness I'll mention it. As noted above, curl needs to be able to find this file.

4) The JS file options
These are the last three options above (App.js, serviceWorker.js, index.js). They are optional. If you omit them, your stack traces will have correct file, line and column info, but the actual lines of code will still display the minimized version. If you add them incorrectly, it can cause your upload to fail or your source map to not be applied.

Your source map, near the beginning, will have a `sources` key pointing to an array:
```
"sources":["App.js","serviceWorker.js","index.js"]
```
Those values should be the keys for each of the curl options. The value of each option must be the file location of the unminified, original JS file. This is how the minified lines of code get converted back to the original code. Note that these are file attachment options (prefixed with `@`) and have to point to a real location on disk.

5) Describe and send one source map per curl command
The API expects one source map per request. To upload multiple source maps, call curl for each one. Each of the options must be correct for the specific source map referenced in that call.

6) If you build new files, upload new source maps
Each time you `npm run build`, your fingerprinted file names will change. You will need to re-upload the new source maps with the new names. If no code has changed, you don't have to modify the version string in your config and in your curl uploads. But they do have to match. When you change the version, change it in both places. If your code did change, then you do need to change the version string. You can follow any scheme you want for how to generate the version strings.

**Comment by jarretmoses** [comment]
@waltjones thanks for the detailed description. I did end up writing a script to just run after every prod build to re-upload the source maps manually (since as you said the hashes change). I did however choose to go the `automatic download` route `/sourcemaps/download`. I am curious though Why do you upload `"App.js","serviceWorker.js","index.js"]` Does Rollbar need to know more than just the actual minified file the source map is defined for? Also if I'm note mistaken I can just put a value in for `code_version` and never change it. Though it doesn't seem to be necessary at all (am I mistaken?).

**Comment by waltjones** [comment]
@jarretmoses Great to hear you have it working.

The original files aren't needed in order to get the original file, line, column info. But they are needed in order to show the original code for that line, instead of still showing the minified code.

Re. `code_version`: Because in this case the files have fingerprint strings, the unique code version is probably less (or not) necessary. (I haven't thought through all the edge cases.) For projects without the versioned filenames, it would definitely be necessary.
