### ISSUE TITLE
[question] [react]: reporting to Rollbar in Error Boundaries

### ISSUE THREAD

**Issue by raunofreiberg** [rollbar/rollbar.js#743]
I was playing around with the example of https://codepen.io/rollbar_example/pen/JrMGQq?editors=1011

If I remove the `Rollbar.error(error)` call from `componentDidCatch` in `ErrorBoundary`, the API calls to Rollbar still persist. Also, in the [example](https://rollbar.com/blog/react-error-boundaries/), it shows an example of logging manually in `componentDidCatch`

My question being, is this manual reporting in the lifecycle necessary or is Rollbar listening to errors itself enough? Because all of the errors that I've tried so far still propagate to Rollbar, regardless.

**Comment by waltjones** [comment]
@raunofreiberg Rollbar.js has a global handler for uncaught errors that is enabled when `captureUncaught` is set in your config. For uncaught errors, that is all you would need. But errors inside an error boundary shouldn't bubble up to the uncaught error handler unless they were re-thrown. In other words, when using `componentDidCatch` and when the error is thrown in a child component, you should need the `Rollbar.error(error)` to report the error, because the global handler should never see it.

I'll set up a test here and see what happens.

**Comment by waltjones** [comment]
@raunofreiberg In development mode, React sends the error to `componentDidCatch` _and_ does not actually catch it. In this case, it will also be sent to `onerror` and caught by Rollbar's global handler.

In production mode, it should work as you expect. The error is seen by `componentDidCatch` and is actually caught and will not show up at the global handler.

The development mode behavior seems odd to me, and is poorly documented. (I haven't found it described by an official source.) But it is apparently what the React team intends.
