### ISSUE TITLE
Protecting against Angular error spam

### ISSUE THREAD

**Issue by jpike88** [rollbar/rollbar.js#752]
Angular's current implementation makes using Rollbar a total pain.

I think some sort of built in error spam detection should be implemented, to prevent the Rollbar API from getting hammered.

If an error's signature is identical, you should maybe consider blocking further requests from that particular sender?

Could be this an account setting maybe?

https://github.com/angular/angular/issues/17010

**Comment by waltjones** [comment]
Rollbar.js will silently drop duplicate unhandled errors. (Thrown and not caught.) It will not do this for errors sent to Rollbar by your code, e.g. calling `Rollbar.error()`.

For behavior more specific to your situation, the `checkIgnore()` function allows you to specify exactly how to decide what to ignore. Since `checkIgnore` sees the full stream of Rollbar events, you can use event history for your ignore logic.
