### ISSUE TITLE
"should map the stack" test is failing

### ISSUE THREAD

**Issue by chebum** [rollbar/rollbar.js#785]
Hello,
I wanted to update some dependencies and noticed the "should map the stack" test is failing. To be clear the test is failing with current dependency versions and current source code in "master" branch.
Is it expected behaviour?

And second question. Browser tests require JSON-js dependency. Where can I obtain it?

Thanks,
Ivan

**Comment by waltjones** [comment]
Hi @chebum I'm not seeing the failing test here, but maybe you can push your branch and see if it fails on CI? That way I can also see it and help debug.

JSON-js is a submodule under the vendor dir. Try:
`git submodule update --init`

**Comment by chebum** [comment]
Hi @waltjones I'm sorry for the late reply.

Thank you for the suggestion with submodule updates - it worked.

Regarding the falling test. I have no doubts it passes in the CI. I just wanted to say that cloning the repo (master branch), calling `npm install`, `make `and then `make test` shows non passing test. 

Some authors on github commit with non-passing tests. They know these tests are falling, but aren't ready to fix them yet (or they are the only ones who work on the project). I wasn't sure if that workflow is used for this project or not and thus I asked. I didn't want to waste time trying to figure out why the test isn't passing if the author already knows about it.

**Comment by waltjones** [comment]
@chebum I need a way to see what is failing for you and why. That's why I suggested pushing your branch to see if it fails on CI. Otherwise, describe in more detail what is failing. 

>
This (as described in the README) worked for me with no errors or failing tests:
```
git clone git@github.com:rollbar/rollbar.js.git
cd rollbar.js
git submodule update --init
npm install -D
make
make test
```

> Some authors on github commit with non-passing tests.
I'm not aware of this. If a CI build is canceled (multiple successive merges to master, for example), those cancels are shown as fails, but I'm not aware of any tests/builds that are failing on master or PRs that merged failing.
