### ISSUE TITLE
Implement batch sending a collection of items

### ISSUE THREAD

**Issue by nrutman** [rollbar/rollbar.js#79]
The Rollbar PHP library allows sending a batch of items to Rollbar via the [item_batch](https://github.com/rollbar/rollbar-php/blob/master/src/rollbar.php#L858) API endpoint (btw, does this endpoint exist in the API docs?). For more frequent error reporting (via `warn()` or `info()`) the number of requests to Rollbar quickly adds up.

A queue that stores up items until a certain latency and then bulk sends the items would be a very nice improvement and allow us to implement Rollbar reporting more thoroughly throughout our app.

**Comment by brianr** [comment]
Thanks @nrutman for requesting this. Before we implement this I'd like to do the following:

- document the existing batch endpoints (there are actually two of them)
- review the way batching is currently handled (on the api.rollbar.com side) to make sure we're happy supporting it here as well

We'll update this ticket once work in this library is ready to go forward.

**Comment by coryvirok** [comment]
Although we have a batch endpoint we have deprecated it a little while ago. Sending a group of events together is not really much more performant and causes a lot of different issues on the backend. For example, rate limits become difficult to enforce and are less performant since we cannot just use the access token header to determine if we need to return 429. We need to parse and deserialize all of the occurrences in the batch. Also, retries on the client become much more difficult. 

If there is concern about the performance of multiple HTTPS calls, then using keepalive should solve those. We do indeed use keepalive so the extra API calls are negligible wrt connection performance.

Lastly, for controlling when items are reported to Rollbar, (periodically in bursts) we can code the notifier to handle this. rollbar.js already implements this by using a `setTimeout()` to process queued payloads periodically. The code for that is [here](https://github.com/rollbar/rollbar.js/blob/68ea41f95454426201dd6bc107abe3f87b6ebdac/src/notifier.js#L42).
