### ISSUE TITLE
Unmeaningful descriptions coming from the Rollbar.js SDK in some cases

### ISSUE THREAD

**Issue by ArturMoczulski** [rollbar/rollbar.js#793]
Looks like Rollbar.JS sends gibberish in `exception.description` in some cases.

Historical conversation on the matter including examples: https://app.clubhouse.io/rollbar/story/56302/iterate-on-canva-source-map-issue#activity-56553

**Comment by waltjones** [comment]
@ArturMoczulski Can you provide any detail about this? I can't find anything in that clubhouse link, and no one in the developer community can read it anyway.

**Comment by waltjones** [comment]
Having looked at the example, this is on an older SDK. Newer rollbar-js stores the original exception string in the payload so we can see what got parsed to generate this result. Also, the SDK owns the message field, but the description field is open to the caller. So this may be set by the user, and then we honor that.

Because the description field and message field contents are different, the most likely cause is that this was set by the user.
