### ISSUE TITLE
Bundling node version to client.

### ISSUE THREAD

**Issue by stubar** [rollbar/rollbar.js#822]
Hi we have a CSP rule on our domain which is beyond my control.  It doesn't allow cloudfare.  So I have been bundling the node version to the browser.  It appears to be working Ok. Just wondering if there are any pitfalls with this approach?

**Comment by waltjones** [comment]
If you're using webpack or another front end bundler, it is probably picking up the `browser` key from package.json: `"browser": "dist/rollbar.umd.min.js"` This should work fine for browser environments, and isn't the build used for Node.js.

If you want to use the snippet + rollbar.min.js, and can host the file yourself, set `rollbarJsUrl` in your config to your rollbar.min.js location and the snippet will use it instead of the default CDN location.

Either of these approaches should work fine. If for any reason you really are bundling the Node build of Rollbar.js, the handler for uncaught errors won't work. There may be other issues as well. I expect you are getting the correct build as described above though.
