### ISSUE TITLE
Application has long startup delay when upgrading to version 2.20.0 from version 2.16.2 

### ISSUE THREAD

**Issue by dovidgef** [rollbar/rollbar.js#923]
After we upgraded our Express.js application to use `rollbar.js` version `2.20.0` we are now experiencing 
an over 10 second delay on our application startup. 
Previously when we were using version `2.16.2` it started up nearly instantly.

Any ideas?

**Comment by waltjones** [comment]
Any change in Rollbar config?

This has been tested with simple Express apps with no start up delays.

**Comment by dovidgef** [comment]
We had added the `locals` property, but with and without this property we
experienced this delay.

**Comment by waltjones** [comment]
In your ./node_modules/rollbar/src/server/rollbar.js line 19, you can try commenting or removing `var Locals = require('./locals');` This shouldn't require any other code change as long as locals is off in the config. (if locals is on, it will throw.)

I don't know if this is causing your issue, but that would a quick way to verify.

**Comment by seangarner** [comment]
We've had a similar issue that @svedbg and I have been looking into.  Our issue is caused by this:

> The initial version of this feature supports both caught and uncaught exceptions and promise rejections. Nested exceptions and trace chains are supported.

Specifically the "caught" part.  In our app it's whilst loading a large collection of json schemas.  They support json pointers which it searches for using a try/catch.  https://github.com/whitlockjc/json-refs/blob/d7f1ddab22f75bf1c1d2ce30c35178ee8f136edc/index.js#L225-L237

It'll do that on every single property on the schema and we have 100s of schemas; probably 10,000s of properties.  When we change the [following line](https://github.com/rollbar/rollbar.js/pull/902/files#diff-581d424a84dd32dd8b2dbb7c6f668035e26fe3ffb9c137cc4d515cd24d65bcc1R40) to use `{ state: 'uncaught'}` then our app starts up properly.  I'm not sure what the use-case is for tracking caught exceptions, but perhaps that needs re-evaluating, or at the very least made optional and defaulted to off with a big fat warning on it.

**Comment by waltjones** [comment]
The doc for this feature highlights this (throw/catch in non-error code paths) and recommends evaluating your situation:

> when throw/catch are used as a control mechanism in non-error code paths, care should be taken to ensure enabling locals capture won’t cause performance issues. If in doubt, run performance benchmarks with and without the feature enabled.

https://docs.rollbar.com/docs/nodejs#enabling-local-variables-in-stack-traces

These reports are appreciated, and we're working on an update that will address some scenarios.

**Comment by waltjones** [comment]
v2.21.0, just released, has updated config options that may be helpful in your situation.

Note: the locals module is now loaded separately and is passed into the Rollbar config. See the updated doc here. https://docs.rollbar.com/docs/nodejs#enabling-local-variables-in-stack-traces

For people who are only interested in locals for uncaught errors, the new `locals.uncaughtOnly` option bypasses virtually all of the V8 Inspector code path for caught errors. Its perf measurements are essentially the same as with local capture disabled.

The `locals.enabled` option allows enabling locals capture dynamically after app init or only at a specific time of interest. Both flags (`uncaughtOnly` and `enabled`) can be updated dynamically via `Rollbar.configure()`.

**Comment by seangarner** [comment]
Thanks Walt, we'll give it a try soon.

**Comment by waltjones** [comment]
I expect this is resolved, but if not please reopen.
